version: 0.2
phases:
  install:
    commands:
      - pip install -r requirements.txt
      - pip install pytest
  build:
    commands:
      - pytest -q --junitxml=test-results/junit.xml
reports:
  pytest_reports:
    files:
      - test-results/junit.xml
    file-format: JUNITXML
